### ISSUE TITLE
why when access selector becomes null

### ISSUE THREAD

**Issue by SCGamesNetwork** [SOF3/Capital#30]
Code:

use SOFe\Capital\{Capital, CapitalException, LabelSet};

class Main extends PluginBase {
  private $selector;

  protected function onEnable() : void {
    Capital::api("0.1.0", function(Capital $api) {
      $this->selector = $api->completeConfig($this->getConfig()->get("selector"));
    });
  }
}

and if i var_dump($this->selector);
returned null
but if i var_dump in Capital completeConfig it returned Object

**Comment by SOF3** [comment]
Capital initializes asynchronously. Your closure only gets run after Capital is initialized, which needs to wait for e.g. the Capital database to finish running CREATE TABLE queries.

Therefore, always use `$this->selector` inside a `Capital::api` block. `Capital::api()` is guaranteed to be FIFO, so subsequent calls to `Capital::api` can use an initialized `$this->selector`.
