### ISSUE TITLE
Contact you

### ISSUE THREAD

**Issue by 0ylz1** [SOF3/Capital#47]
Can you give me your discord please i want private plugin

**Comment by 0ylz1** [comment]
I mean i want you to make private plugin for me from scratch

**Comment by 0ylz1** [comment]
Like MiniGames and other’s…

**Comment by SOF3** [comment]
minigames can be made from public plugins as well. and there is no reason to make something from scratch when there is already something and you just need to fix it; restarting from scratch will not give you any better than stepping into the same river once again.

plus... what's the fun of making minigames plugins? I've grown bored of those like 7 years ago... making interesting API plugins is much more interesting!

**Comment by 0ylz1** [comment]
> 

Okay i need API plugin from scratch give me your discord please! I come to you cuz you a very good developer

**Comment by SOF3** [comment]
That API plugin is called Capital, to download it, navigate back to the repo page and visit the Poggit link.
