### ISSUE TITLE
Readme mistakes

### ISSUE THREAD

**Issue by Gewinum** [SOF3/Capital#48]
the smallest issue in this repo lol

i think not And, its and
![Screenshot_2022-08-25-12-39-15-44](https://user-images.githubusercontent.com/78866820/186618168-70f03d98-f54a-47f9-8c38-7f223aeab803.jpg)
no slashes
![Screenshot_2022-08-25-12-40-20-13](https://user-images.githubusercontent.com/78866820/186618176-88c91c7f-6692-4759-837b-3632fe3ec8b0.jpg)
issue, not isuse
![Screenshot_2022-08-25-12-41-00-75](https://user-images.githubusercontent.com/78866820/186618181-76ac9650-0e7c-4a0f-a85b-027b3fe5787a.jpg)

**Comment by SOF3** [comment]
please send pull requests.
